/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProspectingRouteImport } from './routes/_authenticated/prospecting'
import { Route as AuthenticatedPresentationRouteImport } from './routes/_authenticated/presentation'
import { Route as AuthenticatedPipelineAnalyticsRouteImport } from './routes/_authenticated/pipeline-analytics'
import { Route as AuthenticatedPermitsRouteImport } from './routes/_authenticated/permits'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedJobQuotesRouteImport } from './routes/_authenticated/job-quotes'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedAiFeaturesRouteImport } from './routes/_authenticated/ai-features'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectingRoute =
  AuthenticatedProspectingRouteImport.update({
    id: '/prospecting',
    path: '/prospecting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPresentationRoute =
  AuthenticatedPresentationRouteImport.update({
    id: '/presentation',
    path: '/presentation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPipelineAnalyticsRoute =
  AuthenticatedPipelineAnalyticsRouteImport.update({
    id: '/pipeline-analytics',
    path: '/pipeline-analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPermitsRoute = AuthenticatedPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobQuotesRoute = AuthenticatedJobQuotesRouteImport.update({
  id: '/job-quotes',
  path: '/job-quotes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiFeaturesRoute = AuthenticatedAiFeaturesRouteImport.update({
  id: '/ai-features',
  path: '/ai-features',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/ai-features': typeof AuthenticatedAiFeaturesRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/job-quotes': typeof AuthenticatedJobQuotesRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/permits': typeof AuthenticatedPermitsRoute
  '/pipeline-analytics': typeof AuthenticatedPipelineAnalyticsRoute
  '/presentation': typeof AuthenticatedPresentationRoute
  '/prospecting': typeof AuthenticatedProspectingRoute
  '/reports': typeof AuthenticatedReportsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/ai-features': typeof AuthenticatedAiFeaturesRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/job-quotes': typeof AuthenticatedJobQuotesRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/permits': typeof AuthenticatedPermitsRoute
  '/pipeline-analytics': typeof AuthenticatedPipelineAnalyticsRoute
  '/presentation': typeof AuthenticatedPresentationRoute
  '/prospecting': typeof AuthenticatedProspectingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/ai-features': typeof AuthenticatedAiFeaturesRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/job-quotes': typeof AuthenticatedJobQuotesRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/permits': typeof AuthenticatedPermitsRoute
  '/_authenticated/pipeline-analytics': typeof AuthenticatedPipelineAnalyticsRoute
  '/_authenticated/presentation': typeof AuthenticatedPresentationRoute
  '/_authenticated/prospecting': typeof AuthenticatedProspectingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/activities'
    | '/ai-features'
    | '/communications'
    | '/companies'
    | '/contacts'
    | '/job-quotes'
    | '/opportunities'
    | '/permits'
    | '/pipeline-analytics'
    | '/presentation'
    | '/prospecting'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/activities'
    | '/ai-features'
    | '/communications'
    | '/companies'
    | '/contacts'
    | '/job-quotes'
    | '/opportunities'
    | '/permits'
    | '/pipeline-analytics'
    | '/presentation'
    | '/prospecting'
    | '/reports'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/activities'
    | '/_authenticated/ai-features'
    | '/_authenticated/communications'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/job-quotes'
    | '/_authenticated/opportunities'
    | '/_authenticated/permits'
    | '/_authenticated/pipeline-analytics'
    | '/_authenticated/presentation'
    | '/_authenticated/prospecting'
    | '/_authenticated/reports'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospecting': {
      id: '/_authenticated/prospecting'
      path: '/prospecting'
      fullPath: '/prospecting'
      preLoaderRoute: typeof AuthenticatedProspectingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/presentation': {
      id: '/_authenticated/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof AuthenticatedPresentationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline-analytics': {
      id: '/_authenticated/pipeline-analytics'
      path: '/pipeline-analytics'
      fullPath: '/pipeline-analytics'
      preLoaderRoute: typeof AuthenticatedPipelineAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permits': {
      id: '/_authenticated/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof AuthenticatedPermitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/job-quotes': {
      id: '/_authenticated/job-quotes'
      path: '/job-quotes'
      fullPath: '/job-quotes'
      preLoaderRoute: typeof AuthenticatedJobQuotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-features': {
      id: '/_authenticated/ai-features'
      path: '/ai-features'
      fullPath: '/ai-features'
      preLoaderRoute: typeof AuthenticatedAiFeaturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAiFeaturesRoute: typeof AuthenticatedAiFeaturesRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedJobQuotesRoute: typeof AuthenticatedJobQuotesRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedPermitsRoute: typeof AuthenticatedPermitsRoute
  AuthenticatedPipelineAnalyticsRoute: typeof AuthenticatedPipelineAnalyticsRoute
  AuthenticatedPresentationRoute: typeof AuthenticatedPresentationRoute
  AuthenticatedProspectingRoute: typeof AuthenticatedProspectingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAiFeaturesRoute: AuthenticatedAiFeaturesRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedJobQuotesRoute: AuthenticatedJobQuotesRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedPermitsRoute: AuthenticatedPermitsRoute,
  AuthenticatedPipelineAnalyticsRoute: AuthenticatedPipelineAnalyticsRoute,
  AuthenticatedPresentationRoute: AuthenticatedPresentationRoute,
  AuthenticatedProspectingRoute: AuthenticatedProspectingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
